const POPULAR_WALLETS = [
  { id: 'metamask', name: 'MetaMask', icon: '🦊', description: 'Popular browser extension wallet' },
  { id: 'trust', name: 'Trust Wallet', icon: '🛡️', description: 'Mobile-first crypto wallet' },
  { id: 'coinbase', name: 'Coinbase Wallet', icon: '🔵', description: 'User-friendly crypto wallet' },
  { id: 'phantom', name: 'Phantom', icon: '👻', description: 'Solana ecosystem wallet' },
  { id: 'binance', name: 'Binance Chain Wallet', icon: '🟡', description: 'Binance Smart Chain wallet' },
  { id: 'walletconnect', name: 'WalletConnect', icon: '🔗', description: 'Connect any mobile wallet' },
  { id: 'exodus', name: 'Exodus', icon: '🚀', description: 'Multi-currency desktop wallet' },
  { id: 'atomic', name: 'Atomic Wallet', icon: '⚛️', description: 'Decentralized multi-asset wallet' },
  { id: 'electrum', name: 'Electrum', icon: '⚡', description: 'Lightweight Bitcoin wallet' },
  { id: 'ledger', name: 'Ledger Live', icon: '📊', description: 'Hardware wallet companion' },
  { id: 'trezor', name: 'Trezor Suite', icon: '🔐', description: 'Hardware wallet interface' },
  { id: 'myetherwallet', name: 'MyEtherWallet', icon: '💎', description: 'Ethereum wallet interface' },
  { id: 'rainbow', name: 'Rainbow', icon: '🌈', description: 'Ethereum wallet with DeFi focus' },
  { id: 'argent', name: 'Argent', icon: '🏛️', description: 'Smart contract wallet' },
  { id: 'imtoken', name: 'imToken', icon: '🎯', description: 'Multi-blockchain wallet' },
  { id: 'tokenpocket', name: 'TokenPocket', icon: '💰', description: 'Multi-chain wallet' },
  { id: 'safepal', name: 'SafePal', icon: '🔒', description: 'Hardware and software wallet' },
  { id: 'keplr', name: 'Keplr', icon: '🌌', description: 'Cosmos ecosystem wallet' },
  { id: 'terra', name: 'Terra Station', icon: '🌍', description: 'Terra blockchain wallet' },
  { id: 'solflare', name: 'Solflare', icon: '☀️', description: 'Solana wallet' },
  { id: 'slope', name: 'Slope', icon: '📈', description: 'Solana mobile wallet' },
  { id: 'mathwallet', name: 'MathWallet', icon: '🧮', description: 'Multi-platform crypto wallet' },
  { id: 'enjin', name: 'Enjin Wallet', icon: '🎮', description: 'Gaming-focused wallet' },
  { id: 'status', name: 'Status', icon: '💬', description: 'Ethereum wallet with messaging' },
  { id: 'pillar', name: 'Pillar', icon: '🏗️', description: 'Personal data locker wallet' },
  { id: 'unstoppable', name: 'Unstoppable Wallet', icon: '🚫', description: 'Non-custodial multi-coin wallet' },
  { id: 'edge', name: 'Edge', icon: '🔺', description: 'Mobile crypto wallet' },
  { id: 'blockchain', name: 'Blockchain.com', icon: '⛓️', description: 'Popular web wallet' },
  { id: 'jaxx', name: 'Jaxx Liberty', icon: '💫', description: 'Multi-platform wallet' },
  { id: 'breadwallet', name: 'BRD', icon: '🍞', description: 'Simple crypto wallet' },
  { id: 'coinomi', name: 'Coinomi', icon: '🪙', description: 'Multi-coin mobile wallet' },
  { id: 'guarda', name: 'Guarda', icon: '🛡️', description: 'Multi-currency wallet' },
  { id: 'zelcore', name: 'Zelcore', icon: '⚡', description: 'Multi-asset wallet' },
  { id: 'bitpay', name: 'BitPay', icon: '💳', description: 'Bitcoin wallet with card' },
  { id: 'luno', name: 'Luno', icon: '🌙', description: 'Bitcoin and Ethereum wallet' },
  { id: 'wasabi', name: 'Wasabi Wallet', icon: '🌶️', description: 'Privacy-focused Bitcoin wallet' },
  { id: 'samurai', name: 'Samourai Wallet', icon: '🥷', description: 'Privacy Bitcoin wallet' },
  { id: 'bluewallet', name: 'BlueWallet', icon: '🔵', description: 'Bitcoin Lightning wallet' },
  { id: 'green', name: 'Green Wallet', icon: '🟢', description: 'Blockstream Green wallet' },
  { id: 'muun', name: 'Muun', icon: '🌕', description: 'Bitcoin Lightning wallet' },
  { id: 'phoenix', name: 'Phoenix', icon: '🔥', description: 'Lightning Network wallet' },
  { id: 'yoroi', name: 'Yoroi', icon: '🏮', description: 'Cardano wallet' },
  { id: 'daedalus', name: 'Daedalus', icon: '🏛️', description: 'Full-node Cardano wallet' },
  { id: 'adalite', name: 'AdaLite', icon: '💎', description: 'Cardano web wallet' },
  { id: 'nami', name: 'Nami', icon: '🌊', description: 'Cardano browser wallet' },
  { id: 'temple', name: 'Temple', icon: '🏛️', description: 'Tezos wallet' },
  { id: 'kukai', name: 'Kukai', icon: '🌺', description: 'Tezos web wallet' },
  { id: 'galleon', name: 'Galleon', icon: '⛵', description: 'Tezos desktop wallet' },
  { id: 'algorand', name: 'Algorand Wallet', icon: '🔷', description: 'Official Algorand wallet' },
  { id: 'myalgo', name: 'MyAlgo', icon: '🔹', description: 'Algorand web wallet' },
  { id: 'polkadot', name: 'Polkadot.js', icon: '⚫', description: 'Polkadot ecosystem wallet' },
  { id: 'talisman', name: 'Talisman', icon: '🔮', description: 'Polkadot parachain wallet' },
  { id: 'subwallet', name: 'SubWallet', icon: '🌐', description: 'Polkadot multichain wallet' },
  { id: 'fearless', name: 'Fearless Wallet', icon: '💪', description: 'Polkadot mobile wallet' },
  { id: 'nova', name: 'Nova Wallet', icon: '⭐', description: 'Next-gen Polkadot wallet' },
  { id: 'near', name: 'NEAR Wallet', icon: '🔺', description: 'NEAR Protocol wallet' },
  { id: 'sender', name: 'Sender Wallet', icon: '📤', description: 'NEAR web wallet' },
  { id: 'harmony', name: 'Harmony One Wallet', icon: '🎵', description: 'Harmony blockchain wallet' },
  { id: 'elrond', name: 'Elrond Wallet', icon: '⚡', description: 'Elrond network wallet' },
  { id: 'maiar', name: 'Maiar', icon: '🌟', description: 'Elrond mobile wallet' },
  { id: 'avalanche', name: 'Avalanche Wallet', icon: '🏔️', description: 'Avalanche ecosystem wallet' },
  { id: 'core', name: 'Core', icon: '🔥', description: 'Avalanche browser extension' },
  { id: 'ronin', name: 'Ronin Wallet', icon: '⚔️', description: 'Axie Infinity sidechain wallet' },
  { id: 'glow', name: 'Glow', icon: '✨', description: 'Solana validator wallet' },
  { id: 'coin98', name: 'Coin98', icon: '🔄', description: 'Multi-chain DeFi wallet' },
  { id: 'safeware', name: 'Safeware', icon: '🔐', description: 'Security-focused wallet' },
  { id: 'bitkeep', name: 'BitKeep', icon: '🗝️', description: 'Multi-chain Web3 wallet' },
  { id: 'onto', name: 'ONTO', icon: '🎯', description: 'Ontology blockchain wallet' },
  { id: 'cyano', name: 'Cyano Wallet', icon: '🔬', description: 'Ontology browser wallet' },
  { id: 'owallet', name: 'OWallet', icon: '⭕', description: 'Ontology mobile wallet' },
  { id: 'neon', name: 'Neon Wallet', icon: '🌈', description: 'NEO blockchain wallet' },
  { id: 'o3', name: 'O3 Wallet', icon: '⭕', description: 'Multi-chain NEO wallet' },
  { id: 'neoline', name: 'NeoLine', icon: '📈', description: 'NEO browser extension' },
  { id: 'scatter', name: 'Scatter', icon: '🌪️', description: 'EOS ecosystem wallet' },
  { id: 'anchor', name: 'Anchor', icon: '⚓', description: 'EOS desktop wallet' },
  { id: 'wombat', name: 'Wombat', icon: '🐨', description: 'EOS gaming wallet' },
  { id: 'tokenary', name: 'Tokenary', icon: '💎', description: 'macOS Safari crypto wallet' },
  { id: 'frame', name: 'Frame', icon: '🖼️', description: 'Desktop Ethereum wallet' },
  { id: 'gnosis', name: 'Gnosis Safe', icon: '🏛️', description: 'Multi-signature wallet' },
  { id: 'portis', name: 'Portis', icon: '🚪', description: 'Web3 wallet SDK' },
  { id: 'fortmatic', name: 'Fortmatic', icon: '🎩', description: 'Web3 wallet with phone auth' },
  { id: 'torus', name: 'Torus', icon: '🔵', description: 'Social login Web3 wallet' },
  { id: 'authereum', name: 'Authereum', icon: '🔑', description: 'Meta-transaction wallet' },
  { id: 'dapper', name: 'Dapper', icon: '🎭', description: 'Flow blockchain wallet' },
  { id: 'blocto', name: 'Blocto', icon: '🧊', description: 'Flow and multi-chain wallet' },
  { id: 'lilico', name: 'Lilico', icon: '🌸', description: 'Flow browser extension wallet' },
  { id: 'finnie', name: 'Finnie', icon: '🐕', description: 'Koii network wallet' },
  { id: 'frontier', name: 'Frontier', icon: '🏔️', description: 'DeFi and NFT wallet' },
  { id: 'alpha', name: 'Alpha Wallet', icon: '🐺', description: 'Ethereum mobile wallet' },
  { id: 'eidoo', name: 'Eidoo', icon: '🔷', description: 'Multi-currency mobile wallet' },
  { id: 'walleth', name: 'WallETH', icon: '📱', description: 'Android Ethereum wallet' },
  { id: 'dharma', name: 'Dharma', icon: '☸️', description: 'DeFi-focused mobile wallet' },
  { id: 'monero', name: 'Monero GUI', icon: '🔒', description: 'Official Monero wallet' },
  { id: 'cake', name: 'Cake Wallet', icon: '🍰', description: 'Monero and Bitcoin wallet' },
  { id: 'monerujo', name: 'Monerujo', icon: '👁️', description: 'Android Monero wallet' },
  { id: 'feather', name: 'Feather Wallet', icon: '🪶', description: 'Lightweight Monero wallet' },
  { id: 'zcash', name: 'Zcash Wallet', icon: '🛡️', description: 'Official Zcash wallet' },
  { id: 'zecwallet', name: 'ZecWallet', icon: '⚡', description: 'Full-featured Zcash wallet' },
  { id: 'nighthawk', name: 'Nighthawk', icon: '🦅', description: 'Mobile Zcash wallet' },
  { id: 'dash', name: 'Dash Core', icon: '💨', description: 'Official Dash wallet' },
  { id: 'dashpay', name: 'DashPay', icon: '💸', description: 'Dash mobile wallet' },
  { id: 'litecoin', name: 'Litecoin Core', icon: '🥈', description: 'Official Litecoin wallet' },
  { id: 'loafwallet', name: 'LoafWallet', icon: '🍞', description: 'Litecoin mobile wallet' },
  { id: 'dogecoin', name: 'Dogecoin Core', icon: '🐕', description: 'Official Dogecoin wallet' },
  { id: 'multidoge', name: 'MultiDoge', icon: '🐶', description: 'Lightweight Dogecoin wallet' },
  { id: 'uniswap', name: 'Uniswap Wallet', icon: '🦄', description: 'Uniswap mobile wallet' },
  { id: '1inch', name: '1inch Wallet', icon: '1️⃣', description: 'DeFi aggregator wallet' },
  { id: 'metamask_mobile', name: 'MetaMask Mobile', icon: '📱', description: 'Mobile version of MetaMask' },
  { id: 'trustwallet_desktop', name: 'Trust Wallet Desktop', icon: '🖥️', description: 'Desktop Trust Wallet app' },
  { id: 'brave_wallet', name: 'Brave Wallet', icon: '🦁', description: 'Built-in Brave browser wallet' },
  { id: 'opera_wallet', name: 'Opera Wallet', icon: '🎭', description: 'Opera browser crypto wallet' },
  { id: 'rabby', name: 'Rabby', icon: '🐰', description: 'Multi-chain browser extension' },
  { id: 'xdefi', name: 'XDEFI', icon: '❌', description: 'Multi-chain DeFi wallet' },
  { id: 'enkrypt', name: 'Enkrypt', icon: '🔐', description: 'Multi-chain browser wallet' },
  { id: 'backpack', name: 'Backpack', icon: '🎒', description: 'Solana-first wallet' },
  { id: 'sollet', name: 'Sollet', icon: '🌞', description: 'Solana web wallet' },
  { id: 'math_extension', name: 'Math Wallet Extension', icon: '🧮', description: 'Browser extension version' },
  { id: 'coinhub', name: 'CoinHub', icon: '🌐', description: 'Multi-currency wallet' },
  { id: 'spatium', name: 'Spatium', icon: '🌌', description: 'Multi-blockchain wallet' },
  { id: 'keystone', name: 'Keystone', icon: '🗝️', description: 'Air-gapped hardware wallet' },
  { id: 'coolwallet', name: 'CoolWallet', icon: '❄️', description: 'Card-shaped hardware wallet' },
  { id: 'ellipal', name: 'ELLIPAL', icon: '🛡️', description: 'Air-gapped hardware wallet' },
  { id: 'keepkey', name: 'KeepKey', icon: '🔑', description: 'Hardware wallet by ShapeShift' },
  { id: 'bitbox', name: 'BitBox', icon: '📦', description: 'Swiss hardware wallet' },
  { id: 'secux', name: 'SecuX', icon: '🔒', description: 'Hardware wallet with touch screen' },
  { id: 'cobo', name: 'Cobo Vault', icon: '🏦', description: 'Air-gapped hardware wallet' },
  { id: 'dcent', name: 'D\'CENT', icon: '💎', description: 'Biometric hardware wallet' },
  { id: 'ngrave', name: 'NGRAVE', icon: '⚱️', description: 'Ultra-secure hardware wallet' },
  { id: 'gridplus', name: 'GridPlus', icon: '⚡', description: 'Lattice hardware wallet' },
  { id: 'coldcard', name: 'Coldcard', icon: '🧊', description: 'Bitcoin-only hardware wallet' },
  { id: 'foundation', name: 'Foundation Passport', icon: '🛂', description: 'Open-source hardware wallet' },
  { id: 'jade', name: 'Blockstream Jade', icon: '💚', description: 'Bitcoin hardware wallet' },
  { id: 'tangem', name: 'Tangem', icon: '💳', description: 'Card-based hardware wallet' },
  { id: 'fireblocks', name: 'Fireblocks', icon: '🔥', description: 'Institutional wallet platform' },
  { id: 'bitgo', name: 'BitGo', icon: '🏢', description: 'Enterprise crypto wallet' },
  { id: 'copper', name: 'Copper', icon: '🔶', description: 'Institutional custody solution' },
  { id: 'anchorage', name: 'Anchorage Digital', icon: '⚓', description: 'Regulated crypto custody' },
  { id: 'prime_trust', name: 'Prime Trust', icon: '🏦', description: 'Qualified custodian wallet' },
  { id: 'gemini_custody', name: 'Gemini Custody', icon: '♊', description: 'Institutional custody service' },
  { id: 'fidelity', name: 'Fidelity Digital Assets', icon: '🏛️', description: 'Traditional finance crypto custody' },
  { id: 'bakkt', name: 'Bakkt', icon: '🥖', description: 'Digital asset platform wallet' },
  { id: 'voyager', name: 'Voyager', icon: '🚀', description: 'Crypto trading platform wallet' },
  { id: 'celsius', name: 'Celsius', icon: '🌡️', description: 'Crypto lending platform wallet' },
  { id: 'nexo', name: 'Nexo', icon: '🔗', description: 'Crypto lending wallet' },
  { id: 'blockfi', name: 'BlockFi', icon: '📊', description: 'Crypto interest account' },
  { id: 'compound', name: 'Compound Finance', icon: '🏦', description: 'DeFi lending protocol wallet' },
  { id: 'aave', name: 'Aave', icon: '👻', description: 'DeFi lending platform' },
  { id: 'yearn', name: 'Yearn Finance', icon: '🌾', description: 'DeFi yield optimization' },
  { id: 'curve', name: 'Curve Finance', icon: '📈', description: 'Stablecoin DEX wallet' },
  { id: 'balancer', name: 'Balancer', icon: '⚖️', description: 'Automated portfolio manager' },
  { id: 'sushiswap', name: 'SushiSwap', icon: '🍣', description: 'Decentralized exchange wallet' },
  { id: 'pancakeswap', name: 'PancakeSwap', icon: '🥞', description: 'BSC decentralized exchange' },
  { id: 'quickswap', name: 'QuickSwap', icon: '⚡', description: 'Polygon DEX wallet' },
  { id: 'traderjoe', name: 'Trader Joe', icon: '☕', description: 'Avalanche DEX wallet' },
  { id: 'raydium', name: 'Raydium', icon: '☀️', description: 'Solana DEX and AMM' },
  { id: 'serum', name: 'Serum', icon: '🧪', description: 'Solana DEX wallet' },
  { id: 'orca', name: 'Orca', icon: '🐋', description: 'Solana DEX wallet' },
  { id: 'jupiter', name: 'Jupiter', icon: '🪐', description: 'Solana swap aggregator' },
  { id: 'osmosis', name: 'Osmosis', icon: '🌊', description: 'Cosmos DEX wallet' },
  { id: 'terraswap', name: 'Terraswap', icon: '🌍', description: 'Terra DEX wallet' },
  { id: 'astroport', name: 'Astroport', icon: '🚀', description: 'Terra DeFi hub' },
  { id: 'anchor_protocol', name: 'Anchor Protocol', icon: '⚓', description: 'Terra savings protocol' },
  { id: 'mirror', name: 'Mirror Protocol', icon: '🪞', description: 'Terra synthetic assets' },
  { id: 'thorchain', name: 'THORChain', icon: '⚡', description: 'Cross-chain DEX' },
  { id: 'rango', name: 'Rango Exchange', icon: '🔄', description: 'Cross-chain DEX aggregator' },
  { id: 'hop', name: 'Hop Protocol', icon: '🐰', description: 'Layer 2 bridge' },
  { id: 'synapse', name: 'Synapse Protocol', icon: '🧠', description: 'Cross-chain bridge' },
  { id: 'multichain', name: 'Multichain', icon: '⛓️', description: 'Cross-chain router protocol' },
  { id: 'stargate', name: 'Stargate Finance', icon: '🌟', description: 'Omnichain liquidity transport' },
  { id: 'wormhole', name: 'Wormhole', icon: '🕳️', description: 'Cross-chain bridge' },
  { id: 'polygon_bridge', name: 'Polygon Bridge', icon: '🔺', description: 'Ethereum to Polygon bridge' },
  { id: 'arbitrum_bridge', name: 'Arbitrum Bridge', icon: '🔵', description: 'Ethereum Layer 2 bridge' },
  { id: 'optimism_gateway', name: 'Optimism Gateway', icon: '🔴', description: 'Optimistic rollup bridge' },
  { id: 'loopring', name: 'Loopring', icon: '⭕', description: 'Ethereum Layer 2 wallet' },
  { id: 'zksync', name: 'zkSync', icon: '⚡', description: 'Ethereum Layer 2 scaling' },
  { id: 'starknet', name: 'StarkNet', icon: '⭐', description: 'Ethereum Layer 2 solution' },
  { id: 'immutable', name: 'Immutable X', icon: '❌', description: 'NFT Layer 2 solution' },
  { id: 'dydx', name: 'dYdX', icon: '📊', description: 'Decentralized derivatives exchange' },
  { id: 'gmx', name: 'GMX', icon: '📈', description: 'Decentralized perpetual exchange' },
  { id: 'perpetual', name: 'Perpetual Protocol', icon: '♾️', description: 'Decentralized perpetuals' },
  { id: 'mango', name: 'Mango Markets', icon: '🥭', description: 'Solana derivatives trading' },
  { id: 'drift', name: 'Drift Protocol', icon: '🏎️', description: 'Solana perpetuals DEX' },
  { id: 'ribbon', name: 'Ribbon Finance', icon: '🎀', description: 'Structured products protocol' },
  { id: 'opyn', name: 'Opyn', icon: '🛡️', description: 'DeFi options protocol' },
  { id: 'hegic', name: 'Hegic', icon: '🦔', description: 'On-chain options trading' },
  { id: 'dopex', name: 'Dopex', icon: '💊', description: 'Decentralized options exchange' },
  { id: 'lyra', name: 'Lyra', icon: '🎵', description: 'Options AMM protocol' },
  { id: 'premia', name: 'Premia', icon: '💎', description: 'Options trading platform' },
  { id: 'nexus_mutual', name: 'Nexus Mutual', icon: '🛡️', description: 'Decentralized insurance' },
  { id: 'cover', name: 'Cover Protocol', icon: '☂️', description: 'DeFi insurance marketplace' },
  { id: 'unslashed', name: 'Unslashed Finance', icon: '🔓', description: 'Decentralized insurance' },
  { id: 'chainlink', name: 'Chainlink', icon: '🔗', description: 'Oracle network wallet' },
  { id: 'band', name: 'Band Protocol', icon: '🎵', description: 'Cross-chain data oracle' },
  { id: 'api3', name: 'API3', icon: '🔌', description: 'Decentralized API network' },
  { id: 'tellor', name: 'Tellor', icon: '📡', description: 'Decentralized oracle network' },
  { id: 'dia', name: 'DIA', icon: '💎', description: 'Open financial data platform' },
  { id: 'gitcoin', name: 'Gitcoin', icon: '🏗️', description: 'Open source funding platform' },
  { id: 'snapshot', name: 'Snapshot', icon: '📸', description: 'Decentralized voting platform' },
  { id: 'aragon', name: 'Aragon', icon: '🏛️', description: 'DAO creation platform' },
  { id: 'colony', name: 'Colony', icon: '🐝', description: 'DAO platform for organizations' },
  { id: 'moloch', name: 'Moloch DAO', icon: '👹', description: 'Minimalist DAO framework' },
  { id: 'compound_governance', name: 'Compound Governance', icon: '🗳️', description: 'DeFi governance platform' },
  { id: 'maker_governance', name: 'MakerDAO Governance', icon: '🏛️', description: 'DAI stablecoin governance' },
  { id: 'aave_governance', name: 'Aave Governance', icon: '👻', description: 'Aave protocol governance' },
  { id: 'uniswap_governance', name: 'Uniswap Governance', icon: '🦄', description: 'UNI token governance' },
  { id: 'ens', name: 'ENS', icon: '🌐', description: 'Ethereum Name Service' },
  { id: 'unstoppable_domains', name: 'Unstoppable Domains', icon: '🚫', description: 'Blockchain domain service' },
  { id: 'handshake', name: 'Handshake', icon: '🤝', description: 'Decentralized naming protocol' },
  { id: 'ipfs', name: 'IPFS', icon: '🌐', description: 'InterPlanetary File System' },
  { id: 'filecoin', name: 'Filecoin', icon: '📁', description: 'Decentralized storage network' },
  { id: 'arweave', name: 'Arweave', icon: '🏹', description: 'Permanent data storage' },
  { id: 'storj', name: 'Storj', icon: '☁️', description: 'Decentralized cloud storage' },
  { id: 'siacoin', name: 'Siacoin', icon: '💾', description: 'Decentralized storage platform' },
  { id: 'golem', name: 'Golem', icon: '🤖', description: 'Decentralized computing network' },
  { id: 'render', name: 'Render Network', icon: '🎨', description: 'Decentralized GPU rendering' },
  { id: 'livepeer', name: 'Livepeer', icon: '📹', description: 'Decentralized video streaming' },
  { id: 'theta', name: 'Theta Network', icon: '📺', description: 'Decentralized video delivery' }
];